openapi: 3.0.0
info:
  description: api.video is an API that encodes on the go to facilitate immediate
    playback, enhancing viewer streaming experiences across multiple devices and platforms.
    You can stream live or on-demand online videos within minutes.
  title: api.video
  version: "1"
servers:
- description: Production server
  url: https://ws.api.video
- description: Test server `all videos are watermarked, and deleted after 24 hours.
  url: https://sandbox.api.video
paths:
  /auth/api-key:
    post:
      description: |-
        To get started, submit your API key in the body of your request. api.video returns an access token that is valid for one hour (3600 seconds). A refresh token is also returned. View a [tutorial](https://api.video/blog/tutorials/authentication-tutorial) on authentication.
        All tutorials using the [authentication endpoint](https://api.video/blog/endpoints/authenticate)
      operationId: POST_auth-api-key
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authenticate-payload'
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                response:
                  value:
                    token_type: Bearer
                    expires_in: 3600
                    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjUyZWM4NWUyMjFkODZjOWI0NDQ5NzBhMjQwMzUyOWQ4MDQyNGQ3ZmJjYjFlYWM2MjVlM2VkMjI2YWRlNTcxMDY2NDUyZDc0NjdhN2E4NjI0In0.eyJhdWQiOiJsaWJjYXN0IiwianRpIjoiNTJlYzg1ZTIyMWQ4NmM5YjQ0NDk3MGEyNDAzNTI5ZDgwNDI0ZDdmYmNiMWVhYzYyNWUzZWQyMjZhZGU1NzEwNjY0NTJkNzQ2N2E3YTg2MjQiLCJpYXQiOjE1MjUyNzYxNDcsIm5iZiI6MTUyNTI3NjE0NywiZXhwIjoxNTI1Mjc5NzQ3LCJzdWIiOiJ1c01vbml0b3IiLCJzY29wZXMiOlsibW9uaXRvci5saWJjYXN0LmNvbSJdLCJjb250ZXh0Ijp7InVzZXIiOiJ1c01vbml0b3IiLCJwcm9qZWN0IjoicHJNb25pdG9yIiwibWVtYmVyIjoibWVNb25pdG9yIn19.rUvishDNyJLNlI4W5VmguNecm5KD2uZgPkKJQbaqw-cJbSrVxkSbiKYtk_E3cz3WT7-IS2yFTsYN3uIo5Rbit8_HftweyEp2bdBRI8yjR6oZZ1sNJJXswISN1i2kk4r-aaxu7Xxf_LtsjOMUj_YZsvcc2nqBXPKjHbJCJryx3DDJaIcymOqao7nhQaCCQyrQooAXNTYs4E9fWN1dC_x2O-zok5TuG-xhEW-umwxfSUMWNgSTkz38ACceQ0PCJSgB3jqjDH4MwC7B3ppEPZuK5E6JhKeyRlalswRyYq3UQPnVeMTam7YQHsuTgbehF6WySW8i44o7V_MCe9hjPdp-WA
                    refresh_token: def50200a28d88fb9aaa921be78eeb5604b071101a334899a7d5fc7492cf8ea752962ddc8961fe5c126101d4ecacd980396eb2fd494995b812dffcb98256c4277f790d1f658fc2d2e34f350740544e5232d69d68d34c648271d706c5e7049adac0b1832d0fdf71809715cc7e97fa63f65966deadb501a55ff469b0fd23a637cb6acbe9d9b8594a17f09efc2efeed82984764a0065d5e29c950c7b081a61ba2aaa192be3085c400ee37eac50fa9320ce2cfe8916c8165418d23e9f91b6a5c8515e1d74ee193a5a1ca01954fbff27361c20184240be2359e0afbed0bf1c762cf872450b5e8b5d4704f4fd9583e4470adc98409dd42965709712806bd9019378a72eea0b4912ce684ffd833db5806ab84174f905db2a75380071d004615c944bb8f8c4045cce7234c2be9a2330522cf7f067b8e58f57cffb6edb4b7ef91313e12bcde47e5e76ceee7fa52990132288f345d33ed917ae4fd54b7284f8964d898e97e1ee3bc4157f75d7fee63976e4be66ac1ec32ef74afa533f0eb593523f226cbec57d196ac8962
              schema:
                $ref: '#/components/schemas/access-token'
          description: Success
        "400":
          content:
            application/json:
              examples:
                response:
                  value:
                    type: https://docs.api.video/docs/authenticationinvalid_credentials
                    title: The user credentials were incorrect.
                    name: ""
                    status: 400
              schema:
                $ref: '#/components/schemas/bad-request'
          description: Bad Request
      summary: Authenticate
      tags:
      - Authentication
      x-client-action: authenticate
      x-client-hidden: true
      x-readme:
        code-samples:
        - language: go
          code: |
            //With the api.video API clients, authentication is taken care of with each client created.
            // You get to skip this step!
        - language: node
          code: |
            //With the api.video API clients, authentication is taken care of with each client created.
            // You get to skip this step!
        - language: php
          code: |
            //With the api.video API clients, authentication is taken care of with each client created.
            // You get to skip this step!
        - language: python
          code: |
            #With the api.video API clients, authentication is taken care of with each client created.
            # You get to skip this step!
        - language: java
          code: |
            //With the api.video API clients, authentication is taken care of with each client created.
            // You get to skip this step!
        - language: csharp
          code: |
            //With the api.video API clients, authentication is taken care of with each client created.
            // You get to skip this step!
      x-contentType: application/json
      x-accepts: application/json
  /auth/refresh:
    post:
      description: "Use the refresh endpoint with the refresh token you received when\
        \ you first authenticated using the api-key endpoint. Send the refresh token\
        \ in the body of your request. The api.video API returns a new access token\
        \ that is valid for one hour (3600 seconds) and a new refresh token. \n"
      operationId: POST_auth-refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/refresh-token-payload'
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                response:
                  value:
                    token_type: Bearer
                    expires_in: 3600
                    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjUyZWM4NWUyMjFkODZjOWI0NDQ5NzBhMjQwMzUyOWQ4MDQyNGQ3ZmJjYjFlYWM2MjVlM2VkMjI2YWRlNTcxMDY2NDUyZDc0NjdhN2E4NjI0In0.eyJhdWQiOiJsaWJjYXN0IiwianRpIjoiNTJlYzg1ZTIyMWQ4NmM5YjQ0NDk3MGEyNDAzNTI5ZDgwNDI0ZDdmYmNiMWVhYzYyNWUzZWQyMjZhZGU1NzEwNjY0NTJkNzQ2N2E3YTg2MjQiLCJpYXQiOjE1MjUyNzYxNDcsIm5iZiI6MTUyNTI3NjE0NywiZXhwIjoxNTI1Mjc5NzQ3LCJzdWIiOiJ1c01vbml0b3IiLCJzY29wZXMiOlsibW9uaXRvci5saWJjYXN0LmNvbSJdLCJjb250ZXh0Ijp7InVzZXIiOiJ1c01vbml0b3IiLCJwcm9qZWN0IjoicHJNb25pdG9yIiwibWVtYmVyIjoibWVNb25pdG9yIn19.rUvishDNyJLNlI4W5VmguNecm5KD2uZgPkKJQbaqw-cJbSrVxkSbiKYtk_E3cz3WT7-IS2yFTsYN3uIo5Rbit8_HftweyEp2bdBRI8yjR6oZZ1sNJJXswISN1i2kk4r-aaxu7Xxf_LtsjOMUj_YZsvcc2nqBXPKjHbJCJryx3DDJaIcymOqao7nhQaCCQyrQooAXNTYs4E9fWN1dC_x2O-zok5TuG-xhEW-umwxfSUMWNgSTkz38ACceQ0PCJSgB3jqjDH4MwC7B3ppEPZuK5E6JhKeyRlalswRyYq3UQPnVeMTam7YQHsuTgbehF6WySW8i44o7V_MCe9hjPdp-WA
                    refresh_token: def50200a28d88fb9aaa921be78eeb5604b071101a334899a7d5fc7492cf8ea752962ddc8961fe5c126101d4ecacd980396eb2fd494995b812dffcb98256c4277f790d1f658fc2d2e34f350740544e5232d69d68d34c648271d706c5e7049adac0b1832d0fdf71809715cc7e97fa63f65966deadb501a55ff469b0fd23a637cb6acbe9d9b8594a17f09efc2efeed82984764a0065d5e29c950c7b081a61ba2aaa192be3085c400ee37eac50fa9320ce2cfe8916c8165418d23e9f91b6a5c8515e1d74ee193a5a1ca01954fbff27361c20184240be2359e0afbed0bf1c762cf872450b5e8b5d4704f4fd9583e4470adc98409dd42965709712806bd9019378a72eea0b4912ce684ffd833db5806ab84174f905db2a75380071d004615c944bb8f8c4045cce7234c2be9a2330522cf7f067b8e58f57cffb6edb4b7ef91313e12bcde47e5e76ceee7fa52990132288f345d33ed917ae4fd54b7284f8964d898e97e1ee3bc4157f75d7fee63976e4be66ac1ec32ef74afa533f0eb593523f226cbec57d196ac8962
              schema:
                $ref: '#/components/schemas/access-token'
          description: Success
        "400":
          content:
            application/json:
              examples:
                response:
                  value:
                    status: 400
                    type: https://docs.api.video/docs/authenticationinvalid_credentials
                    title: The user credentials were incorrect.
                    name: ""
              schema:
                $ref: '#/components/schemas/bad-request'
          description: Bad Request
      summary: Refresh token
      tags:
      - Authentication
      x-client-action: refresh
      x-client-hidden: true
      x-readme:
        code-samples:
        - language: go
          code: |
            //With the api.video API clients, authentication is taken care of with each client created.
            // You get to skip this step!
        - language: node
          code: |
            //With the api.video API clients, authentication is taken care of with each client created.
            // You get to skip this step!
        - language: php
          code: |
            //With the api.video API clients, authentication is taken care of with each client created.
            // You get to skip this step!
        - language: python
          code: |
            #With the api.video API clients, authentication is taken care of with each client created.
            # You get to skip this step!
        - language: java
          code: |
            //With the api.video API clients, authentication is taken care of with each client created.
            // You get to skip this step!
        - language: csharp
          code: |
            //With the api.video API clients, authentication is taken care of with each client created.
            // You get to skip this step!
      x-contentType: application/json
      x-accepts: application/json
  /videos/{videoId}/source:
    post:
      description: "To upload a video to the videoId you created. Replace {videoId}\
        \ with the id you'd like to use, {access_token} with your token, and /path/to/video.mp4\
        \ with the path to the video you'd like to upload. You can only upload your\
        \ video to the videoId once.\nWe offer 2 types of upload: \n* Regular upload\
        \ \n* Progressive upload\nThe latter allows you to split a video source into\
        \ X chunks and send those chunks independently (concurrently or sequentially).\
        \ The 2 main goals for our users are to\n  * allow the upload of video sources\
        \ > 200 MiB (200 MiB = the max. allowed file size for regular upload)\n  *\
        \ allow to send a video source \"progressively\", i.e., before before knowing\
        \ the total size of the video.\n  Once all chunks have been sent, they are\
        \ reaggregated to one source file. The video source is considered as \"completely\
        \ sent\" when the \"last\" chunk is sent (i.e., the chunk that \"completes\"\
        \ the upload).\n```bash\ncurl https://ws.api.video/videos/{videoId}/source\
        \ \\\n  -H 'Authorization: Bearer {access_token}' \\\n  -F file=@/path/to/video.mp4\n\
        \n  ```\nTutorials using [video upload](https://api.video/blog/endpoints/video-upload)."
      operationId: POST_videos-videoId-source
      parameters:
      - description: Enter the videoId you want to use to upload your video.
        example: vi4k0jvEUuaTdRAEjQ4Jfrgz
        explode: false
        in: path
        name: videoId
        required: true
        schema:
          type: string
        style: simple
      - description: "Content-Range can be used if you want to split your file. You\
          \ can do this by parts, or by chunk.\n* If you split your file by parts\
          \ (recommended option), the `Content-Range` header value must match the\
          \ following pattern: `part <part>/<total_parts>`:\n  * `<part>` is a positive\
          \ integer representing the part number. The first sequential part number\
          \ is always 1.\n  * `<total_parts>` is a positive integer representing the\
          \ total parts of the video source. It can also be `*` if or as long as it\
          \ is unknown. Technically, this value is required only one time and cannot\
          \ differ in several requests.\n* If you split your file by bytes, bear in\
          \ mind byte ranges are inclusive, meaning that bytes 0-5242879 represents\
          \ the first 5,242,880 bytes in a file or object. Also, the Content-Range\
          \ header value must match the following pattern: `bytes <from_byte>-<to_byte>/<total_bytes>`:\n\
          \  * `<from_byte>` is a positive integer or 0. It represents the range start\
          \ (aka lower bound), i.e., the first byte of the chunk compared to the total\
          \ bytes composing the full video source. The first sequential range always\
          \ starts at 0.\n  * `<to_byte>` is a positive integer representing the range\
          \ end (aka upper bound), i.e., the last byte of the chunk compared to the\
          \ total bytes composing the full video source.\n  * `<total_bytes>` is a\
          \ positive integer representing the total bytes composing the full video\
          \ source. It can also be `*` if or as long as it is unknown. Technically,\
          \ this value is required only one time and cannot differ in several requests.\n\
          * Ordering and chunk or part size\n  * The order in which the chunks are\
          \ received on our side does not matter. \n    * Example: `part 3/*` then\
          \ `part 2/*` then `part 1/3` works.\n  * The chunks can be sent concurrently.\
          \ We have a lock mechanism to ensure they are still technically processed\
          \ one by one to ensure the \"completion\" check behaves as expected.\n \
          \ * The only chunk that can be smaller than our minimum allowed chunk size\
          \ (5 MiB) is the last sequential one (i.e., the last sequential range for\
          \ the \"byte-range\" system and the last part for the \"part\" system.\n\
          \    * For instance, if your video is 10.5 MiB big, your last chunk would\
          \ be 500 KiB, and that would work. \n    * Another example is if your video\
          \ is 2 MiB big, then your first and last chunk will be 2MiB and that will\
          \ work as well.\n"
        example: bytes 209715200-419430399/524288000 OR part 2/3
        explode: false
        in: header
        name: Content-Range
        required: false
        schema:
          pattern: /(?:bytes (?<from>\d+)-(?<to>\d+)|part (?<part>\d+))\/(?<total>\d+|\*)/
          type: string
        style: simple
        x-client-ignore: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/video-upload-payload'
        required: true
      responses:
        "201":
          content:
            application/json:
              examples:
                response:
                  value:
                    videoId: vi4blUQJFrYWbaG44NChkH27
                    title: Maths video
                    description: An amazing video explaining the string theory.
                    public: false
                    panoramic: false
                    mp4Support: true
                    playerId: pl45KFKdlddgk654dspkze
                    tags:
                    - maths
                    - string theory
                    - video
                    metadata:
                    - key: Author
                      value: John Doe
                    - key: Format
                      value: Tutorial
                    publishedAt: 4665-07-14T23:36:18.598+00:00
                    source:
                      uri: /videos/vi4blUQJFrYWbaG44NChkH27/source
                    assets:
                      iframe: <iframe src="https://embed.api.video/vod/vi4blUQJFrYWbaG44NChkH27"
                        width="100%" height="100%" frameborder="0" scrolling="no"
                        allowfullscreen=""></iframe>
                      player: https://embed.api.video/vod/vi4blUQJFrYWbaG44NChkH27
                      hls: https://cdn.api.video/vod/vi4blUQJFrYWbaG44NChkH27/hls/manifest.m3u8
                      thumbnail: https://cdn.api.video/vod/vi4blUQJFrYWbaG44NChkH27/thumbnail.jpg
                      mp4: https://cdn.api.video/vod/vi4blUQJFrYWbaG44NChkH27/mp4/1080/source.mp4
              schema:
                $ref: '#/components/schemas/video'
          description: Created
        "400":
          content:
            application/json:
              examples:
                response:
                  value:
                    type: https://docs.api.video/docs/filealreadyuploaded
                    title: The source of the video is already uploaded.
                    name: file
                    status: 400
                    problems:
                    - type: https://docs.api.video/docs/filealreadyuploaded
                      title: The source of the video is already uploaded.
                      name: file
                    - type: https://docs.api.video/docs/filealreadyuploaded
                      title: The video xxxx has already been uploaded.
                      name: video
                    - type: https://docs.api.video/docs/filemissing
                      title: There is no uploaded file in the request.
                      name: file
                    - type: https://docs.api.video/docs/multiplefilesuploaded
                      title: There is more than one uploaded file in the request.
                      name: file
              schema:
                $ref: '#/components/schemas/bad-request'
          description: Bad Request
        "404":
          content:
            application/json:
              examples:
                response:
                  value:
                    type: https://docs.api.video/docs/resourcenot_found
                    title: The requested resource was not found.
                    name: videoId
                    status: 404
              schema:
                $ref: '#/components/schemas/not-found'
          description: Not Found
      security:
      - bearerAuth: []
      summary: Upload a video
      tags:
      - Videos
      x-client-action: upload
      x-client-chunk-upload: true
      x-readme:
        code-samples:
        - language: go
          code: "//install the Go API client\n//go get github.com/apivideo/api.video-go-client\n\
            \npackage main\n\nimport (\n    \"context\"\n    \"fmt\"\n    \"os\"\n\
            \    apivideosdk \"github.com/apivideo/api.video-go-client\"\n)\n\nfunc\
            \ main() {\n    client := apivideosdk.ClientBuilder(\"YOUR_API_TOKEN\"\
            ).Build()\n    // if you rather like to use the sandbox environment:\n\
            \    // client := apivideosdk.SandboxClientBuilder(\"YOU_SANDBOX_API_TOKEN\"\
            ).Build()\n\n      videoId := \"vi4k0jvEUuaTdRAEjQ4Jfrgz\" \n    // string\
            \ | Enter the videoId you want to use to upload your video.\n      file\
            \ := os.NewFile(1234, \"some_file\") \n    // *os.File | The path to the\
            \ video you would like to upload. The path must be local. If you want\
            \ to use a video from an online source, you must use the \\\\\\\"/videos\\\
            \\\\\" endpoint and add the \\\\\\\"source\\\\\\\" parameter when you\
            \ create a new video.\n    \n    \n      res, err := client.Videos.UploadFile(videoId,\
            \ file)\n    \n      // you can also use a Reader instead of a File:\n\
            \      // client.Videos.Upload(videoId, fileName, fileReader, fileSize)\n\
            \    \n      if err != nil {\n          fmt.Fprintf(os.Stderr, \"Error\
            \ when calling `Videos.Upload``: %v\\n\", err)\n      }\n      // response\
            \ from `Upload`: Video\n      fmt.Fprintf(os.Stdout, \"Response from `Videos.Upload`:\
            \ %v\\n\", res)\n    }\n      }\n"
        - language: node
          code: "//install the module with npm or yarn\n//npm install @api.video/nodejs-client\
            \ --save\n//yarn add @api.video/nodejs-client\n(async () => {\n    try\
            \ {\n      const client = new ApiVideoClient({ apiKey: \"YOUR_API_TOKEN\"\
            \ });\n      \n      const videoId = 'vi4k0jvEUuaTdRAEjQ4Jfrgz'; // Enter\
            \ the videoId you want to use to upload your video.\n      const file\
            \ = 'BINARY_DATA_HERE'; // The path to the video you would like to upload.\
            \ The path must be local. If you want to use a video from an online source,\
            \ you must use the \\\\\\\"/videos\\\\\\\" endpoint and add the \\\\\\\
            \"source\\\\\\\" parameter when you create a new video.\n      \n    \
            \  // Video\n      const result = await client.videos.upload(videoId,\
            \ file);\n      console.log(result);\n    } catch (e) {\n        console.error(e);\n\
            \    }\n})();\n"
        - language: php
          code: |
            <?php

            use ApiVideo\Client\Model\VideoCreationPayload;

            require __DIR__ . '/vendor/autoload.php';

            $httpClient = new \Symfony\Component\HttpClient\Psr18Client();
            $client = new \ApiVideo\Client(
                                'https://sandbox.api.video',
                                'YOUR_API_TOKEN',
                                $httpClient
                            );

            // create a new video & upload a video file
            $myVideo = $client->videos()->create((new VideoCreationPayload())->setTitle('Uploaded video'));
            $client->videos()->upload($myVideo->getVideoId(), new SplFileObject(__DIR__ . '/../../../tests/resources/558k.mp4'));

            // create a new video & upload a video file using progressive upload (the file is uploaded by parts)
            $myVideo2 = $client->videos()->create((new VideoCreationPayload())->setTitle('Uploaded video (progressive upload)'));

            $progressiveSession = $client->videos()->createUploadProgressiveSession($myVideo2->getVideoId());

            $progressiveSession->uploadPart(new SplFileObject(__DIR__ . '/../../../tests/resources/10m.mp4.part.a'));
            $progressiveSession->uploadPart(new SplFileObject(__DIR__ . '/../../../tests/resources/10m.mp4.part.b'));

            $progressiveSession->uploadLastPart(new SplFileObject(__DIR__ . '/../../../tests/resources/10m.mp4.part.c'));
        - language: python
          code: |
            #install the api.video API client library
            #pip install api.video

            import apivideo
            from apivideo.api import videos_api
            from apivideo.model.bad_request import BadRequest
            from apivideo.model.not_found import NotFound
            from apivideo.model.video import Video
            from apivideo.configuration import Configuration
            from pprint import pprint

            # Enter a context with an instance of the API client
            # When uploading a file you can change the chunk size (in octet)
            configuration = Configuration(chunk_size=10 * 1024 * 1024)
            with apivideo.AuthenticatedApiClient(__API_KEY__, configuration=configuration) as api_client:
                # Create an instance of the API class
                api_instance = videos_api.VideosApi(api_client)
                video_id = "vi4k0jvEUuaTdRAEjQ4Jfrgz" # str | Enter the videoId you want to use to upload your video.
                file = open('/path/to/file', 'rb') # file_type | The path to the video you would like to upload. The path must be local. If you want to use a video from an online source, you must use the \\\"/videos\\\" endpoint and add the \\\"source\\\" parameter when you create a new video.

                # example passing only required values which don't have defaults set
                try:
                    # Upload a video
                    api_response = api_instance.upload(video_id, file)
                    pprint(api_response)
                except apivideo.ApiException as e:
                    print("Exception when calling VideosApi->upload: %s\n" % e)
        - language: java
          code: |
            //dependency addition instructions
            //https://github.com/apivideo/api.video-java-client
            // Import classes:
            import video.api.client.ApiVideoClient;
            import video.api.client.api.ApiException;
            import video.api.client.api.models.*;
            import video.api.client.api.clients.VideosApi;
            import java.util.*;

            public class Example {
              public static void main(String[] args) {
                ApiVideoClient client = new ApiVideoClient("YOUR_API_TOKEN");
                // if you rather like to use the sandbox environment:
                // ApiVideoClient client = new ApiVideoClient("YOU_SANDBOX_API_TOKEN", ApiVideoClient.Environment.SANDBOX);

                VideosApi apiInstance = client.videos();

                String videoId = "vi4k0jvEUuaTdRAEjQ4Jfrgz"; // Enter the videoId you want to use to upload your video.
                File file = new File("/path/to/file"); // The path to the video you would like to upload. The path must be local. If you want to use a video from an online source, you must use the \\\"/videos\\\" endpoint and add the \\\"source\\\" parameter when you create a new video.

                try {
                  Video result = apiInstance.upload(videoId, file);
                  System.out.println(result);
                } catch (ApiException e) {
                  System.err.println("Exception when calling VideosApi#upload");
                  System.err.println("Status code: " + e.getCode());
                  System.err.println("Reason: " + e.getMessage());
                  System.err.println("Response headers: " + e.getResponseHeaders());
                  e.printStackTrace();
                }
              }
            }
        - language: csharp
          code: |
            //install via Nuget
            //Install-Package ApiVideo

            using System.Diagnostics;
            using ApiVideo.Client;

            namespace Example
            {
                public class uploadExample
                {
                    public static void Main()
                    {
                        var basePath = ApiVideoClient.Client.Environment.SANDBOX;
                        var apiKey = "YOUR_API_KEY";

                        var apiInstance = new ApiVideoClient(apiKey,basePath);

                        var videoId = vi4k0jvEUuaTdRAEjQ4Jfrgz;  // string | Enter the videoId you want to use to upload your video.
                        var file = BINARY_DATA_HERE;  // System.IO.Stream | The path to the video you would like to upload. The path must be local. If you want to use a video from an online source, you must use the \\\"/videos\\\" endpoint and add the \\\"source\\\" parameter when you create a new video.
                        var apiVideosInstance = apiInstance.Videos();
                        try
                        {
                            // Upload a video
                            Video result = apiVideosInstance.upload(videoId, file);
                            Debug.WriteLine(result);
                        }
                        catch (ApiException  e)
                        {
                            Debug.Print("Exception when calling VideosApi.upload: " + e.Message );
                            Debug.Print("Status Code: "+ e.ErrorCode);
                            Debug.Print(e.StackTrace);
                        }
                    }
                }
            }
      x-contentType: multipart/form-data
      x-accepts: application/json
  /upload:
    post:
      description: "When given a token, anyone can upload a file to the URI `https://ws.api.video/upload?token=<tokenId>`.\n\
        \nExample with cURL:\n\n```curl\n$ curl  --request POST --url 'https://ws.api.video/upload?token=toXXX'\n\
        \ --header 'content-type: multipart/form-data'\n -F file=@video.mp4\n```\n\
        \nOr in an HTML form, with a little JavaScript to convert the form into JSON:\n\
        ```html\n<!--form for user interaction-->\n<form name=\"videoUploadForm\"\
        \ >\n  <label for=video>Video:</label>\n  <input type=file name=source/><br/>\n\
        \  <input value=\"Submit\" type=\"submit\">\n</form>\n<div></div>\n<!--JS\
        \ takes the form data \n    uses FormData to turn the response into JSON.\n\
        \    then uses POST to upload the video file.\n    Update the token parameter\
        \ in the url to your upload token.\n    -->\n<script>\n   var form = document.forms.namedItem(\"\
        videoUploadForm\");\t\n   form.addEventListener('submit', function(ev) {\n\
        \t ev.preventDefault();\n     var oOutput = document.querySelector(\"div\"\
        ),\n         oData = new FormData(form);\n     var oReq = new XMLHttpRequest();\n\
        \t \n     oReq.open(\"POST\", \"https://ws.api.video/upload?token=toXXX\"\
        , true);\n     oReq.send(oData);\n\t oReq.onload = function(oEvent) {\n  \
        \     if (oReq.status ==201) {\n         oOutput.innerHTML = \"Your video\
        \ is uploaded!<br/>\"  + oReq.response;\n       } else {\n         oOutput.innerHTML\
        \ = \"Error \" + oReq.status + \" occurred when trying to upload your file.<br\
        \ \\/>\";\n       }\n     };\n   }, false);\t\n</script>\n```\n\n\n### Dealing\
        \ with large files\n\nYou can upload large files on api.video with <a href='https://docs.api.video/reference/post_videos-videoid-source'>Progressive\
        \ Upload</a>. Alternatively, if you want to use regular upload, we have created\
        \ a <a href='https://api.video/blog/tutorials/uploading-large-files-with-javascript'>tutorial</a>\
        \ to walk through the steps required."
      operationId: POST_upload
      parameters:
      - description: The unique identifier for the token you want to use to upload
          a video.
        example: to1tcmSFHeYY5KzyhOqVKMKb
        explode: true
        in: query
        name: token
        required: true
        schema:
          type: string
        style: form
      - description: Content-Range represents the range of bytes that will be returned
          as a result of the request. Byte ranges are inclusive, meaning that bytes
          0-999 represents the first 1000 bytes in a file or object.
        example: 'Content-Range: bytes 200-100/5000'
        explode: false
        in: header
        name: Content-Range
        required: false
        schema:
          pattern: ^bytes [0-9]*-[0-9]*\/[0-9]*$
          type: string
        style: simple
        x-client-ignore: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/token-upload-payload'
        required: true
      responses:
        "201":
          content:
            application/json:
              examples:
                response:
                  value:
                    videoId: vi4k0jvEUuaTdRAEjQ4Jfrgz
                    playerId: pl45KFKdlddgk654dspkze
                    title: Maths video
                    description: An amazing video explaining the string theory
                    public: false
                    panoramic: false
                    tags:
                    - maths
                    - string theory
                    - video
                    metadata:
                    - key: Author
                      value: John Doe
                    - key: Format
                      value: Tutorial
                    publishedAt: 4665-07-14T23:36:18.598Z
                    source:
                      uri: /videos/vi4k0jvEUuaTdRAEjQ4Jfrgz/source
                    assets:
                      iframe: <iframe src="https://embed.api.video/vod/vi4blUQJFrYWbaG44NChkH27"
                        width="100%" height="100%" frameborder="0" scrolling="no"
                        allowfullscreen=""></iframe>
                      player: https://embed.api.video/vod/vi4blUQJFrYWbaG44NChkH27
                      hls: https://cdn.api.video/vod/vi4blUQJFrYWbaG44NChkH27/hls/manifest.m3u8
                      thumbnail: https://cdn.api.video/vod/vi4blUQJFrYWbaG44NChkH27/thumbnail.jpg
                      mp4: https://cdn.api.video/vod/vi4blUQJFrYWbaG44NChkH27/mp4/1080/source.mp4
              schema:
                $ref: '#/components/schemas/video'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad-request'
          description: Bad Request
      security: []
      summary: Upload with an upload token
      tags:
      - Videos
      x-client-action: uploadWithUploadToken
      x-client-chunk-upload: true
      x-readme:
        code-samples:
        - language: go
          code: "//The upload will happen on the front end, and not on the backend\
            \ code.  \n//Our [JavaScript uploader(https://docs.api.video/docs/video-uploader)\
            \ is a great place to look for uploading videos with the delegated token.\n\
            //We also have uploaders for a number of [mobile languages](https://docs.api.video/docs/flutter-uploader).\n"
        - language: node
          code: "//The upload will happen on the front end, and not on the backend\
            \ code.  \n//Our [JavaScript uploader(https://docs.api.video/docs/video-uploader)\
            \ is a great place to look for uploading videos with the delegated token.\n\
            //We also have uploaders for a number of [mobile languages](https://docs.api.video/docs/flutter-uploader).\n"
        - language: python
          code: "#The upload will happen on the front end, and not on the backend\
            \ code.  \n#Our [JavaScript uploader(https://docs.api.video/docs/video-uploader)\
            \ is a great place to look for uploading videos with the delegated token.\n\
            #We also have uploaders for a number of [mobile languages](https://docs.api.video/docs/flutter-uploader).\n"
        - language: java
          code: "//The upload will happen on the front end, and not on the backend\
            \ code.  \n//Our [JavaScript uploader(https://docs.api.video/docs/video-uploader)\
            \ is a great place to look for uploading videos with the delegated token.\n\
            //We also have uploaders for a number of [mobile languages](https://docs.api.video/docs/flutter-uploader).\n"
        - language: csharp
          code: "//The upload will happen on the front end, and not on the backend\
            \ code.  \n//Our [JavaScript uploader(https://docs.api.video/docs/video-uploader)\
            \ is a great place to look for uploading videos with the delegated token.\n\
            //We also have uploaders for a number of [mobile languages](https://docs.api.video/docs/flutter-uploader).\n"
      x-contentType: multipart/form-data
      x-accepts: application/json
components:
  parameters:
    current-page:
      description: 'Choose the number of search results to return per page. Minimum
        value: 1'
      example: 2
      explode: true
      in: query
      name: currentPage
      required: false
      schema:
        default: 1
        type: integer
      style: form
    page-size:
      description: Results per page. Allowed values 1-100, default is 25.
      example: 30
      explode: true
      in: query
      name: pageSize
      required: false
      schema:
        default: 25
        type: integer
      style: form
  schemas:
    access-token:
      example:
        access_token: est
        token_type: qui nulla l
        refresh_token: cillum
        expires_in: 3600
      properties:
        access_token:
          description: The access token containing security credentials allowing you
            to acccess the API. The token lasts for one hour.
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjUyZWM4NWUyMjFkODZjOWI0NDQ5NzBhMjQwMzUyOWQ4MDQyNGQ3ZmJjYjFlYWM2MjVlM2VkMjI2YWRlNTcxMDY2NDUyZDc0NjdhN2E4NjI0In0.eyJhdWQiOiJsaWJjYXN0IiwianRpIjoiNTJlYzg1ZTIyMWQ4NmM5YjQ0NDk3MGEyNDAzNTI5ZDgwNDI0ZDdmYmNiMWVhYzYyNWUzZWQyMjZhZGU1NzEwNjY0NTJkNzQ2N2E3YTg2MjQiLCJpYXQiOjE1MjUyNzYxNDcsIm5iZiI6MTUyNTI3NjE0NywiZXhwIjoxNTI1Mjc5NzQ3LCJzdWIiOiJ1c01vbml0b3IiLCJzY29wZXMiOlsibW9uaXRvci5saWJjYXN0LmNvbSJdLCJjb250ZXh0Ijp7InVzZXIiOiJ1c01vbml0b3IiLCJwcm9qZWN0IjoicHJNb25pdG9yIiwibWVtYmVyIjoibWVNb25pdG9yIn19.rUvishDNyJLNlI4W5VmguNecm5KD2uZgPkKJQbaqw-cJbSrVxkSbiKYtk_E3cz3WT7-IS2yFTsYN3uIo5Rbit8_HftweyEp2bdBRI8yjR6oZZ1sNJJXswISN1i2kk4r-aaxu7Xxf_LtsjOMUj_YZsvcc2nqBXPKjHbJCJryx3DDJaIcymOqao7nhQaCCQyrQooAXNTYs4E9fWN1dC_x2O-zok5TuG-xhEW-umwxfSUMWNgSTkz38ACceQ0PCJSgB3jqjDH4MwC7B3ppEPZuK5E6JhKeyRlalswRyYq3UQPnVeMTam7YQHsuTgbehF6WySW8i44o7V_MCe9hjPdp-WA
          type: string
        token_type:
          default: bearer
          description: The type of token you have.
          type: string
        refresh_token:
          description: A token you can use to get the next access token when your
            current access token expires.
          example: def50200a28d88fb9aaa921be78eeb5604b071101a334899a7d5fc7492cf8ea752962ddc8961fe5c126101d4ecacd980396eb2fd494995b812dffcb98256c4277f790d1f658fc2d2e34f350740544e5232d69d68d34c648271d706c5e7049adac0b1832d0fdf71809715cc7e97fa63f65966deadb501a55ff469b0fd23a637cb6acbe9d9b8594a17f09efc2efeed82984764a0065d5e29c950c7b081a61ba2aaa192be3085c400ee37eac50fa9320ce2cfe8916c8165418d23e9f91b6a5c8515e1d74ee193a5a1ca01954fbff27361c20184240be2359e0afbed0bf1c762cf872450b5e8b5d4704f4fd9583e4470adc98409dd42965709712806bd9019378a72eea0b4912ce684ffd833db5806ab84174f905db2a75380071d004615c944bb8f8c4045cce7234c2be9a2330522cf7f067b8e58f57cffb6edb4b7ef91313e12bcde47e5e76ceee7fa52990132288f345d33ed917ae4fd54b7284f8964d898e97e1ee3bc4157f75d7fee63976e4be66ac1ec32ef74afa533f0eb593523f226cbec57d196ac8962
          type: string
        expires_in:
          description: Lists the time in seconds when your access token expires. It
            lasts for one hour.
          type: integer
      title: AccessToken
      type: object
    bad-request:
      properties:
        type:
          type: string
        title:
          type: string
        name:
          type: string
        status:
          type: integer
        problems:
          items:
            $ref: '#/components/schemas/bad-request'
          type: array
          uniqueItems: true
      title: BadRequest
      type: object
    not-found:
      properties:
        type:
          type: string
        title:
          type: string
        name:
          type: string
        status:
          type: integer
      title: NotFound
      type: object
    video:
      example:
        videoId: vi4k0jvEUuaTdRAEjQ4Jfrgz
        title: Maths video
        description: An amazing video explaining the string theory
        tags:
        - maths
        - string theory
        - video
        metadata:
        - key: Author
          value: John Doe
        - key: Format
          value: Tutorial
        createdAt: 4251-03-03T12:52:03.085Z
        publishedAt: 4665-07-14T23:36:18.598Z
        actions:
        - video_delete
        - video_download
        - video_update
      properties:
        videoId:
          description: The unique identifier of the video object.
          example: vi4k0jvEUuaTdRAEjQ4Prklg
          type: string
        createdAt:
          description: When a video was created, presented in ISO-8601 format.
          format: date-time
          type: string
        title:
          description: |
            The title of the video content.
          example: Maths video
          type: string
        description:
          description: |
            A description for the video content.
          example: An amazing video explaining string theory.
          type: string
        publishedAt:
          description: The date and time the API created the video. Date and time
            are provided using ISO-8601 UTC format.
          example: 2019-12-16T08:25:51+00:00
          type: string
        updatedAt:
          description: The date and time the video was updated. Date and time are
            provided using ISO-8601 UTC format.
          example: 2019-12-16T08:25:51+00:10
          format: date-time
          type: string
        tags:
          description: "One array of tags (each tag is a string) in order to categorize\
            \ a video. Tags may include spaces. \n"
          example: '"tags": ["maths", "string theory", "video"]'
          items:
            type: string
          type: array
        metadata:
          description: |
            Metadata you can use to categorise and filter videos. Metadata is a list of dictionaries, where each dictionary represents a key value pair for categorising a video. [Dynamic Metadata](https://api.video/blog/endpoints/dynamic-metadata) allows you to define a key that allows any value pair.
          example: '[{"key":"Author", "value":"John Doe"}, {"key":"Format", "value":"Tutorial"}]'
          items:
            $ref: '#/components/schemas/metadata'
          type: array
        source:
          $ref: '#/components/schemas/video-source'
        assets:
          $ref: '#/components/schemas/video-assets'
        playerId:
          description: |
            The id of the player that will be applied on the video.
          example: pl45KFKdlddgk654dspkze
          type: string
        public:
          description: |
            Defines if the content is publicly reachable or if a unique token is needed for each play session. Default is true. Tutorials on [private videos](https://api.video/blog/endpoints/private-videos).
          example: false
          type: boolean
        panoramic:
          description: |
            Defines if video is panoramic.
          example: false
          type: boolean
        mp4Support:
          description: |
            This lets you know whether mp4 is supported. If enabled, an mp4 URL will be provided in the response for the video.
          example: true
          type: boolean
      required:
      - videoId
      title: Video
      type: object
    authenticate-payload:
      example:
        apiKey: 9VxMaPgsaFg7EBqmuspSzF7
      properties:
        apiKey:
          description: Your account API key. You can use your sandbox API key, or
            you can use your production API key.
          type: string
      required:
      - apiKey
      title: ApiKey
      type: object
    refresh-token-payload:
      example:
        refreshToken: def502005346d9cc2bd79a7793ab5bdabfefcaabfbb8c253f14733f1262077e1a3f38c4751d6d20f590c3784e531a82adc11f05fc1949aa46d5575aaa99cb84b9334ba66ac773576b5d7a418937ae337de62811d086dd42ad1164b12f87d67be6ffea18f2d50be9b95697b21c4d3c4372849bdb2287259cb80541570e913691a08b2fa33c85885930de15cebea627fc09f0255562ab3d39d87d4ff8fc02b00e252afcd480421dec7de9d1411176bcf669c527762e22294b453bc9ea06e9fa8ba5b873feb2ee14ce0a6a6ddd4b78c580631e210e9b9387265dc2bec9478a66a09dcdce1c40d2f856689e9d81742c9628a0b87b359e0b218ea1f07427eef89f999e47af89792f598e05847bd008fddc32ee63f4a601ffb4cd2ad08977f1c854ec358238322c918f05aa5a41f8a171dee497218408abc8283473f6112aeed7310815416a0fa36c63667e0ed014fa40b8992891bf58bae400d901c01450101c88f4978938ad138adc19cfe5698d60fd82cb27c586f6a8f70f4393c7c9e579df8739d46d249fb76d7
      properties:
        refreshToken:
          description: |
            The refresh token is either the first refresh token you received when you authenticated with the auth/api-key endpoint, or it's the refresh token from the last time you used the auth/refresh endpoint. Place this in the body of your request to obtain a new access token (which is valid for an hour) and a new refresh token.
          type: string
      required:
      - refreshToken
      title: RefreshToken
      type: object
    metadata:
      properties:
        key:
          description: The constant that defines the data set.
          example: Color
          type: string
        value:
          description: A variable which belongs to the data set.
          example: Green
          type: string
      title: Metadata
      type: object
      x-client-all-args-constructor: true
    video-upload-payload:
      properties:
        file:
          description: The path to the video you would like to upload. The path must
            be local. If you want to use a video from an online source, you must use
            the "/videos" endpoint and add the "source" parameter when you create
            a new video.
          format: binary
          type: string
          x-client-chunk-upload: "true"
      required:
      - file
      type: object
    token-upload-payload:
      properties:
        file:
          description: The path to the video you want to upload.
          format: binary
          type: string
          x-client-chunk-upload: "true"
        videoId:
          description: The video id returned by the first call to this endpoint in
            a large video upload scenario.
          type: string
          x-client-ignore: true
          x-client-copy-from-response: true
      required:
      - file
      title: tokenUploadPayload
      type: object
    video-source-live-stream-link:
      properties:
        rel:
          type: string
        uri:
          type: string
      type: object
    video-source-live-stream:
      description: This appears if the video is from a Live Record.
      properties:
        liveStreamId:
          description: The unique identifier for the live stream.
          example: li400mYKSgQ6xs7taUeSaEKr
          type: string
        links:
          items:
            $ref: '#/components/schemas/video-source-live-stream-link'
          type: array
      type: object
    video-source:
      description: Source information about the video.
      properties:
        uri:
          description: The URL where the video is stored.
          example: /videos/vi4k0jvEUuaTdRAEjQ4Prklg/source
          type: string
        type:
          type: string
        liveStream:
          $ref: '#/components/schemas/video-source-live-stream'
      title: VideoSource
      type: object
    video-assets:
      description: Collection of details about the video object that you can use to
        work with the video object.
      properties:
        hls:
          description: This is the manifest URL. For HTTP Live Streaming (HLS), when
            a HLS video stream is initiated, the first file to download is the manifest.
            This file has the extension M3U8, and provides the video player with information
            about the various bitrates available for streaming.
          format: uri
          type: string
        iframe:
          description: Code to use video from a third party website
          example: <iframe src="//embed.api.video/c188ed58-3403-46a2-b91b-44603d10b2c9?token=831a9bd9-9f50-464c-a369-8e9d914371ae"
            width="100%" height="100%" frameborder="0" scrolling="no" allowfullscreen=""></iframe>
          type: string
        player:
          description: Raw url of the player.
          example: https://embed.api.video/1b9d6ae8-8f57-4b6d-8552-d636926b4f5f?token=831a9bd9-9f50-464c-a369-8e9d914371ae
          format: uri
          type: string
        thumbnail:
          description: Poster of the video.
          example: https://cdn.api.video/stream/831a9bd9-9f50-464c-a369-8e9d914371ae/thumbnail.jpg
          format: uri
          type: string
        mp4:
          description: Available only if mp4Support is enabled. Raw mp4 url.
          example: https://cdn.api.video/vod/vi4k0jvEUuaTdRAEjQ4Jfrgz/token/8fd70443-d9f0-45d2-b01c-12c8cfc707c9/mp4/720/source.mp4
          format: uri
          type: string
      title: VideoAssets
      type: object
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
x-client-base-paths:
  production: https://ws.api.video
  sandbox: https://sandbox.api.video
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
  - curl
  - go
  - node
  - php
  - python

